### ISSUE TITLE
Unable to get event props for a custom event

### ISSUE THREAD

**Issue by mohan-nishit** [marko-ogg/plausible-api#1]
Hi.

I'm trying to use the package to get custom events' (with props) data. The props are like `store` etc.

In the support class `Property`, I could only find constants mapping `event:name` and `event:page`.
On postman, I'm able to query the data by passing `property=event:props:store` to the query parameters.

Is there any plan to support this kind of functionality?

**Comment by marko-ogg** [comment]
Hi @mohan-nishit, thank you for reporting this!

The support has been added in https://github.com/devarts/plausible-php/releases/tag/v3.0.0

**Comment by marko-ogg** [comment]
Note, supported filters check has been dropped from `Devarts\PlausiblePHP\Support\Filter::add`, so you can pass any custom property to filter by, and there is also now method `addEventCustomProperty`.

In `PlausibleAPI`, method `getBreakdown` was already supporting custom properties to be passed.

Feel free to point out if there is still something missing regarding what was raised here.
